// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ANCModes } from "./ANCModes.d";
import type { BatteryStatus } from "./BatteryStatus.d";

export interface TrayDeviceStatus { is_connected: boolean, left_status: BatteryStatus, right_status: BatteryStatus, anc_mode: ANCModes, }