/*
 Generated by typeshare 1.6.0
*/

export interface BatteryLevel {
	left: number;
	right: number;
}

export interface ChargingStatus {
	left: boolean;
	right: boolean;
}

/**
 * Sound Mode byte alignment
 * | Byte | Description           | Values |
 * |------|-----------------------|--------|
 * | 0    | Mode                  | 0 for ANC, 1 for Transparency, 2 for Normal |
 * | 1    | ANC Sub-mode          | 0/1/2/3 - Transport,Outdoor,Indoor,Custom  |
 * | 2    | Transparency Sub-mode | 0 for Fully Transparent 1 for Vocal for Transparency |
 * | 3    | Sub-mode value        | Used only in the Custom mode |
 */
export type SoundMode = 
	| { type: "NoiseCancelling", mode: ANCModes }
	| { type: "NormalMode", mode?: undefined }
	| { type: "TransparencyMode", mode: TransparencyModes };

export interface SoundcoreDeviceState {
	eq: EQValues;
	sound_mode: SoundMode;
	charging_status: ChargingStatus;
	battery_level: BatteryLevel;
}

export type ANCModes = 
	| { type: "Outdoor", value?: undefined }
	| { type: "Indoor", value?: undefined }
	| { type: "Custom", value: number }
	| { type: "Transport", value?: undefined };

export enum TransparencyModes {
	Vocal = "Vocal",
	FullyTransparent = "FullyTransparent",
}

