/*
 Generated by typeshare 1.0.0
*/

export interface DeviceFeatures {
	profiles: SupportedANCProfiles[];
}

export enum SupportedANCProfiles {
	Normal = "Normal",
	AncTransportMode = "AncTransportMode",
	AncOutdoorMode = "AncOutdoorMode",
	AncIndoorMode = "AncIndoorMode",
	AncCustomValue = "AncCustomValue",
	TransparencyFullyTransparentMode = "TransparencyFullyTransparentMode",
	TransparencyVocalMode = "TransparencyVocalMode",
}

