/*
 Generated by typeshare 1.0.0
*/

export interface NewTrayDeviceStatus {
	is_connected: boolean;
	left_status: BatteryStatus;
	right_status: BatteryStatus;
	anc_mode: ANCModes;
}

export interface DeviceFeatures {
	profiles: SupportedANCProfiles[];
}

export enum SupportedModel {
	A3027 = "A3027",
	A3028 = "A3028",
	A3029 = "A3029",
	A3040 = "A3040",
	A3935 = "A3935",
	A3951 = "A3951",
}

export enum SupportedANCProfiles {
	Normal = "Normal",
	AncTransportMode = "AncTransportMode",
	AncOutdoorMode = "AncOutdoorMode",
	AncIndoorMode = "AncIndoorMode",
	AncCustomValue = "AncCustomValue",
	TransparencyFullyTransparentMode = "TransparencyFullyTransparentMode",
	TransparencyVocalMode = "TransparencyVocalMode",
}

