/*
 Generated by typeshare 1.0.0
*/

export interface BthScanResult {
	name: string;
	address: string;
	is_connected: boolean;
}

export interface NewTrayDeviceStatus {
	is_connected: boolean;
	charging: BatteryCharging;
	level: BatteryLevel;
	anc_mode: ANCModes;
}

export interface DeviceFeatures {
	profiles: SupportedANCProfiles[];
}

export type ANCModes = 
	| { mode: "NormalMode", value?: undefined }
	| { mode: "AncTransportMode", value?: undefined }
	| { mode: "AncOutdoorMode", value?: undefined }
	| { mode: "AncIndoorMode", value?: undefined }
	| { mode: "AncCustomValue", value: number }
	| { mode: "TransparencyFullyTransparentMode", value?: undefined }
	| { mode: "TransparencyVocalMode", value?: undefined };

export enum SupportedANCProfiles {
	Normal = "Normal",
	AncTransportMode = "AncTransportMode",
	AncOutdoorMode = "AncOutdoorMode",
	AncIndoorMode = "AncIndoorMode",
	AncCustomValue = "AncCustomValue",
	TransparencyFullyTransparentMode = "TransparencyFullyTransparentMode",
	TransparencyVocalMode = "TransparencyVocalMode",
}

