/*
 Generated by typeshare 1.6.0
*/

export interface BthScanResult {
	name: string;
	address: string;
	is_connected: boolean;
}

export type ANCModes = 
	| { mode: "NormalMode", value?: undefined }
	| { mode: "AncTransportMode", value?: undefined }
	| { mode: "AncOutdoorMode", value?: undefined }
	| { mode: "AncIndoorMode", value?: undefined }
	| { mode: "AncCustomValue", value: number }
	| { mode: "TransparencyFullyTransparentMode", value?: undefined }
	| { mode: "TransparencyVocalMode", value?: undefined };

export interface NewTrayDeviceStatus {
	is_connected: boolean;
	charging: BatteryCharging;
	level: BatteryLevel;
	anc_mode: ANCModes;
}

export enum SupportedANCProfiles {
	Normal = "Normal",
	AncTransportMode = "AncTransportMode",
	AncOutdoorMode = "AncOutdoorMode",
	AncIndoorMode = "AncIndoorMode",
	AncCustomValue = "AncCustomValue",
	TransparencyFullyTransparentMode = "TransparencyFullyTransparentMode",
	TransparencyVocalMode = "TransparencyVocalMode",
}

export interface DeviceFeatures {
	profiles: SupportedANCProfiles[];
}

export interface DescriptorResponse {
	name: string;
	mac_address: string;
	model: string;
}

export type SoundcoreRequestMessage = 
	| { type: "GetDescriptors", content?: undefined }
	| { type: "OpenDevice", content: DescriptorResponse }
	| { type: "CloseDevice", content?: undefined }
	| { type: "RequestNewState", content?: undefined }
	| { type: "SetSoundMode", content: SoundMode }
	| { type: "SetEQ", content: EQValues };

export type SoundcoreResponseMessage = 
	| { type: "NewState", content: SoundcoreDeviceState }
	| { type: "Descriptors", content: DescriptorResponse[] }
	| { type: "CreationSuccess", content?: undefined }
	| { type: "Error", content: string };

