/*
 Generated by typeshare 1.6.0
*/

export interface BthScanResult {
	name: string;
	address: string;
	is_connected: boolean;
	modelid: SupportedModels;
}

export type ANCModes = 
	| { mode: "NormalMode", value?: undefined }
	| { mode: "AncTransportMode", value?: undefined }
	| { mode: "AncOutdoorMode", value?: undefined }
	| { mode: "AncIndoorMode", value?: undefined }
	| { mode: "AncCustomValue", value: number }
	| { mode: "TransparencyFullyTransparentMode", value?: undefined }
	| { mode: "TransparencyVocalMode", value?: undefined };

export interface NewTrayDeviceStatus {
	is_connected: boolean;
	charging: BatteryCharging;
	level: BatteryLevel;
	anc_mode: ANCModes;
}

