[package]
name = "soundcore-lib"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "soundcore-lib-cli-tool"
path = "src/cli.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.24.2", features = ["time", "macros", "rt-multi-thread"] }
async-trait = "0.1.59"
thiserror = "1.0.37"
bluetooth-lib = { path = "../bluetooth-lib/" }
log = "0.4.17"
typeshare = "1.0.1"
phf = { version = "0.11", default-features = false, features = ["macros"] }
dialoguer = { version = "0.10.3", features = ["fuzzy-select"] }

